# Generated by Django 6.0.1 on 2026-03-02 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_leaverequest_employee_alter_leaverequest_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee_name',
        ),
    ]
